### ISSUE TITLE
Duplicate/incorrect data appear in "Building and Development" Issue Types

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/react-baltcogo#146]
OK, this is a tricky one. It appears that data is being mapped incorrectly for three issues: 
- Grading work without permit
- Electrical work without permit
- Plumbing work without permit

To replicate, choose any of these and submit, then log into Citysourced console and you'll see many of the fields under "Request Details" are duplicated and  contain a mix of address data from the map and from the text fields where the user enters their address.

Here's what it looks like in the console. The red boxes indicate the duplicate/erroneous fields in the console:
![FireShot Capture 100 - CitySourced® Console - Simplifying Civic Engagement™_ - console citysourced net](https://user-images.githubusercontent.com/13049389/62015982-5f55d600-b17d-11e9-90bd-4611b04ef353.png)

I think this is an item from the current app that is not accounted for in the new one. Because of the janky way that the Accela integration had to be set up, each of these issues (Building, Grading, Electrical, and Plumbing) is a separate top-level category in CitySourced. In our app, we combined them into one category instead of showing them 4 different times.

So that might me what's going on here -- our JSON file is set up to combine these into 1 category but the new app might not know how to handle this.

**Comment by martypowell** [comment]
I can take a look at the current app, and will report back. @tmccoy529 @danfox01

**Comment by martypowell** [comment]
So in this case, if a subcategory a property of 'parentId' that should be used as the category otheriwse, you should use the category id as it is now. Here is the logic from the angular app.

```js
{
  name: 'Category',
  id: hasProperty(self.subCategory, 'parentId') ? self.subCategory.parentId : self.category.id,
  value: hasProperty(self.subCategory, 'parentName') ? self.subCategory.parentName : self.category.name
}

@tmccoy529 @danfox01 
```

**Comment by tmccoy529** [comment]
@danfox01 This has been fixed

**Comment by tmccoy529** [comment]
@danfox01 @martypowell this is related to #145

**Comment by danfox01** [comment]
@jdomasky can you please retest all 4 building and development issues and confirm that the extra data is not longer showing in the console?

**Comment by jdomasky** [comment]
@danfox01 OK, proceeding with testing now.

**Comment by jdomasky** [comment]
@danfox01 Retesting in dev is complete. This issue is not resolved.
The only difference I noticed, compared with my testing on July 26, is that #145 seems to be resolved. The first "Your City" field is no longer showing a CitySourced ID number.
As of 10 a.m. today, three of the Building and Development issues are still creating bad records in the console: "Grading work without permit," "Electrical work without permit" and "Plumbing work without permit."
In the records created for the above sub-categories in the console, the "Description," "Your Address," "Your City" and "Your ZIP Code" fields are being duplicated and displaying different values.
As we know, "Building without a permit" looks correct in the console.

**Comment by tmccoy529** [comment]
@danfox01 @jdomasky this should be fixed now.

**Comment by danfox01** [comment]
Thanks! @jdomasky can you please retest?

**Comment by jdomasky** [comment]
OK, will do very shortly.

**Comment by jdomasky** [comment]
Testing was successful. This issue seems to be resolved. However, I'm concerned about the renaming of the Request Type:
Previously, all four Building and Development sub-categories had the same Request Type, which was "Building and Development Issue." Now, each sub-category has a different Request Type:
- Building without a permit = "Building and Development Issue"
- Electrical work without a permit = "Building and Development (Electrical)"
- Grading work without a permit = "Building and Development (Grading)"
- Plumbing work without a permit = "Building and Development (Plumbing)"

I see three potential problems with this:
1. Integration with Accela might be affected, so I asked the Accela team to confirm a Plumbing submission just now.
2. CitySourced analytics or statistics might be affected because we've increased the number of Request Types from 10 to 13. Also, the Request Type for "Building without a permit" didn't change, so any comparisons that are done with past data will show a drop-off for this Request Type, but not a cut-off, which might complicate reporting.
**Recommendation:** Change the Request Type for "Building without a permit" to "Building and Development (Building)".
3. The users of Building and Development records might not see the three new Request Types in the console because they have CitySourced permissions or group assignments that don't include them.
Aside from all this, I like the effect of having the sub-category displayed (parenthetically) in the Service Requests list in the console. I believe it would improve the usability of the console if all of the sub-categories were displayed, but I understand this was done as a workaround.
**Recommendation:** Confirm and correct the affected users' permissions or groups. Inform these users about the change of Request Types.

**Comment by danfox01** [comment]
Thanks Jason! These are all great observations. Dev is now actually working correctly to mirror the behavior in prod -- it was incorrect before. The issue names you noted with the parentheses are supposed to be passed as top level request types. They were previously being included as sub types under Building complaints. We want them displayed on front end that way for simplicity, but they have to go into the back end as separate issues for the Accela integration.

Please let me know if Eric and Matt see any issues, but I believe this is correct. In any event, very good catch on all these differences. If we weren't working in the bizarro world on all this, you'd be 100% right.

**Comment by jdomasky** [comment]
@danfox01 Thanks for the explanation. I understand!
